@startuml
hide footbox
title Remote Code Uploader Workflow

actor User
participant Uploader
participant Espruino
participant Webpage
database Repository


User->Uploader:Loads uploader via browser
activate Uploader
Uploader->Espruino:Connect to Device
activate Espruino
Uploader<--Espruino:Confirm Connection
Uploader->Repository:Connect to server
activate Repository
Uploader<-Repository:Retrieve Remote Code
deactivate Repository
Uploader->Espruino:Write Code to Device
Uploader<-Espruino:Confirm Upload
User<-Uploader:Alert User
deactivate Uploader
User->Webpage:Load page via browser
activate Webpage
Espruino<-Webpage:Connect to Device
Webpage<--Espruino:Confirm Connection
Webpage<->User:Interaction Starts
deactivate Espruino
deactivate Webpage


@enduml
